import os

OLLAMA = os.getenv("OLLAMA_URL", "http://ollama:11434")
XTTS   = os.getenv("XTTS_URL",   "http://xtts:8021")
WHISPER= os.getenv("WHISPER_URL","http://whisper:8022")
COMFY  = os.getenv("COMFY_URL",  "http://comfyui:8188")

IMG_WIDTH  = int(os.getenv("IMG_WIDTH", 768))
IMG_HEIGHT = int(os.getenv("IMG_HEIGHT", 768))
IMG_BATCH  = int(os.getenv("IMG_BATCH", 1))
IMG_STEPS  = int(os.getenv("IMG_STEPS", 20))
IMG_CFG    = float(os.getenv("IMG_CFG", 7.0))
IMG_SAMPLER = os.getenv("IMG_SAMPLER", "dpmpp_2m")
IMG_SCHED   = os.getenv("IMG_SCHED", "karras")
IMG_DENOISE = float(os.getenv("IMG_DENOISE", 1.0))
IMG_CKPT    = os.getenv("IMG_CKPT", "sd_xl_base_1.0.safetensors")
IMG_CLIP_LAYER = int(os.getenv("IMG_CLIP_LAYER", -2))
IMG_PREFIX  = os.getenv("IMG_PREFIX", "comfy_out")
NEGATIVE_DEFAULT = os.getenv("NEGATIVE_DEFAULT", "")
SERVER_URL = os.getenv("SERVER_URL", 'http://192.168.10.169:8188')